### ISSUE TITLE
JIT issue on NikkeTools.exe

### ISSUE THREAD

**Issue by ComplexS1** [FZFalzar/NikkeTools#10]
Been trying to open NikkeTools.exe for awhile now. I do have Net Framework 7.0, and Net Core 3.1 installed. Seems to pull a JIT error, even after repair on both NET tools.

Error shown in cmd prompt is 

Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at NikkeTools.Program.Main(String[] args)

I may be missing something, any help would be appreciated.

**Comment by FZFalzar** [comment]
Instructions said drag and drop folder, did you drag and drop

**Comment by ComplexS1** [comment]
Okay, I did a quick drag and drop from a file in Files/eb. I ended with a error message, I'll post here

Unhandled exception. System.IO.IOException: The parameter is incorrect. : 'C:\Users\jfale\Desktop\eb\0af1ce018a4a2448e2256a47d56575a6'
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.IO.Directory.GetFiles(String path)
   at NikkeTools.Program.Main(String[] args)

I'm guessing my files aren't correct as I ripped em from my Android data folder.

**Comment by FZFalzar** [comment]
Did you drag drop a file or a folder? The program expects a folder instead of a single file

Try making a new folder, put any file inside, then drag and drop the entire folder

You can also run the program in command line, then specify the folder path E.g

> NikkeTools.exe C:\my\folder\

If it still does not work, then I probably can't help other than suggest you completely uninstall the net core runtime and reinstall it. You're the first case I've seen this happening to out of everyone else that managed to run it fine

**Comment by yorigcs** [comment]
Hello friend, I just tried with the files from android version and pc version, both works fine. 
Maybe your files are corrupted?

**Comment by ComplexS1** [comment]
Gotcha, I'll try to rip em again and see if my files stay. If this doesn't work, then I'll try again on my laptop as I'm running a fresh install of Windows 11.

**Comment by FZFalzar** [comment]
I personally use win11 and it runs fine, so its def not an OS issue

**Comment by ComplexS1** [comment]
Okay, I've tried it on 2 Laptops and 2 PC's all running Net Core 3.1. Each one gave the same Kernal error code for CTL. I tried on safe mode, and ran it through VS 2019  via debugging. Seems to crash due to exception, but unsure on what's specifically crashing. Is their anything else that would be needed to run it?

Crash error posted below:
Faulting application name: NikkeTools.exe, version: 1.0.0.0, time stamp: 0x625dbd9d
Faulting module name: KERNELBASE.dll, version: 10.0.22621.963, time stamp: 0x766ca8ae
Exception code: 0xe0434352
Fault offset: 0x00000000000906bc
Faulting process id: 0x0x3D1C
Faulting application start time: 0x0x1D947F5DD8A518E
Faulting application path: C:\Users\jfale\Desktop\Nikke Tools\NikkeTools.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: a94cd5cf-f9aa-4669-ba90-9fef83f669e7
Faulting package full name: 
Faulting package-relative application ID:

**Comment by FZFalzar** [comment]
You will not be able to view the application specific error as the application was built with Release configuration, so debugging information is stripped.

Try building the program from source and running it, I.e open up the solution SLN file, then build/debug from there

**Comment by ComplexS1** [comment]
Alright I ran build/debug and only caught one error. Posting it down below

System.IO.DirectoryNotFoundException
  HResult=0x80070003
  Message=Could not find a part of the path 'C:\Users\jfale\Desktop\NikkeTools-1.1\bin\Debug\netcoreapp3.1\test_enc_dec'.
  Source=System.IO.FileSystem
  StackTrace:
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path)
   at NikkeTools.Program.Main(String[] args) in C:\Users\jfale\Desktop\NikkeTools-1.1\Program.cs:line 58

Although it shows as error, the application opens as normal. Unable to drag/drop files onto cmd as files will not be decrypted.

**Comment by FZFalzar** [comment]
The test_enc_dec is a leftover artifact when I was writing the program, you can remove it via solution settings > debug > arguments

**Comment by ComplexS1** [comment]
Haha, well after deleting the test_enc_dec I testing the files and saw it was giving a error for the debugger. So after seeing your video, and realizing that you're suppose to drop the entire eb folder instead of the single files I tried that and it works! I guess it's user error, and I apologize for wasting your time. I think you might need a video tutorial for idiots like me in the future lol.
