### ISSUE TITLE
coudln't encrypt because of .bundle in file name 

### ISSUE THREAD

**Issue by jhj0517** [FZFalzar/NikkeTools#4]
Hello. Thank you for your beautiful and nice work.

idk why but when I build bundle file via unity, file name is forced to ends with .bundle in my case.
I coudln't encrypt files because of this.

+I just solved this issue by adding one line after line 60.

                if(path.EndsWith("_MOD")) EncryptBundleV1(path);
                **else if(path.EndsWith("_MOD.bundle")) EncryptBundleV1(path);**
                else DecryptBundle(path);

Thank you for your works.

**Comment by FZFalzar** [comment]
Why not just rename the file extension by yourself, this does not require a change to the code
